# Usa una imagen base de PHP
FROM php:8.1-apache

# Habilita el módulo de Apache para .htaccess y rewrite
RUN a2enmod rewrite

# Copia los archivos de tu proyecto al contenedor
# Copia los archivos al contenedor
COPY ./src/class /var/www/html/

# Cambia los permisos para que Apache pueda acceder
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html
# Configura el directorio de trabajo
WORKDIR /var/www/html/

# Expone el puerto 80 (por defecto Apache en Docker)
EXPOSE 80

# Comando para iniciar Apache en segundo plano
CMD ["apache2-foreground"]

