version: '3.7'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - php-network

networks:
  php-network:
    driver: bridge
